name: arkworks benchmarks

on: [push]

env:
  C_KZG_4844_GIT_HASH: '861371629ea1357fbc78208bbd0fdebffac837f1'

jobs:
  benchmarks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]

    steps:
      - uses: actions/checkout@v2

      - name: "[arkworks] Benchmark"
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --manifest-path Arkworks/Cargo.toml

      - name: "[arkworks] Benchmark (parallel)"
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --manifest-path Arkworks/Cargo.toml --features parallel
