name: arkworks tests

on: [push, pull_request, workflow_dispatch]

env:
  C_KZG_4844_GIT_HASH: 'a1d03803059471948e518820afa8518643e1b638'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py_ecc
          pip install PyYAML

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: "[arkworks] Tests (minimal preset)"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path arkworks/Cargo.toml --no-fail-fast --test eip_4844 tests --features minimal-spec

      - name: "[arkworks] Tests (mainnet preset)"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path arkworks/Cargo.toml --no-fail-fast

      - name: "[arkworks] Tests (mainnet preset, parallel)"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path arkworks/Cargo.toml --no-fail-fast --features parallel

      - name: "[arkworks] Tests (c-kzg-4844)"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd arkworks && bash run-c-kzg-4844-tests.sh

      - name: "[arkworks] Tests (c-kzg-4844 parallel)"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd arkworks && bash run-c-kzg-4844-tests.sh --parallel

      - name: "[arkworks] Clippy"
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path arkworks/Cargo.toml --all-targets --all-features -- -D warnings

      - name: "[arkworks] Formatting"
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path arkworks/Cargo.toml -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path kzg-bench/Cargo.toml -- --check
