name: blst-from-scratch benchmarks

on: [push]

env:
  C_KZG_4844_GIT_HASH: '861371629ea1357fbc78208bbd0fdebffac837f1'

jobs:
  benchmarks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py_ecc

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: "[blst-from-scratch] Benchmark"
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --manifest-path blst-from-scratch/Cargo.toml

      - name: "[blst-from-scratch] Benchmark (parallel)"
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --manifest-path blst-from-scratch/Cargo.toml --features parallel

      - name: "[blst-from-scratch] Benchmark (c-kzg-4844)"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd blst-from-scratch && bash run-c-kzg-4844-benches.sh
        
      - name: "[blst-from-scratch] Benchmark (c-kzg-4844 parallel)"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd blst-from-scratch && bash run-c-kzg-4844-benches.sh --parallel
