name: CI Build 
  
on: [push] 
 
jobs: 
  ci: 
 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]

    steps: 
    - uses: actions/checkout@v2 

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy, rustfmt
        
    - name: Run mcl-kzg10-rust tests
      if: matrix.os == 'ubuntu-latest'
      run: |
        cargo test --manifest-path kzg10-rust/kzg-bench/Cargo.toml -- --test-threads 1 

    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --manifest-path kzg-bench/Cargo.toml


