name: mcl benchmarks

on: [push, pull_request, workflow_dispatch]

env:
  C_KZG_4844_GIT_HASH: '9059ba5ae2909d5e8109b873d983ff162c8adbb4'

jobs:
  benchmarks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: "[mcl10-rust] Build native libs for Linux"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd mcl/kzg && bash build.sh

      - name: "[mcl10-rust] Benchmark"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo bench --manifest-path mcl/kzg-bench/Cargo.toml

      - name: "[mcl10-rust] Benchmark (parallel)"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo bench --manifest-path mcl/kzg-bench/Cargo.toml --features mcl_rust/parallel

      #- name: "[mcl10-rust] Benchmark (c-kzg-4844)"
      #  if: matrix.os == 'ubuntu-latest'
      #  run: |
      #    cd mcl/kzg && bash run-c-kzg-4844-benches.sh

      #- name: "[mcl10-rust] Benchmark (c-kzg-4844 parallel)"
      #  if: matrix.os == 'ubuntu-latest'
      #  run: |
      #    cd mcl/kzg && bash run-c-kzg-4844-benches.sh --parallel
