name: zkcrypto benchmarks

on: [push]

env:
  C_KZG_4844_GIT_HASH: '53b38face021d3c60d6d8d14ce3e92989cfea45a'

jobs:
  benchmarks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]

    steps:
      - uses: actions/checkout@v2

      - name: "[zkcrypto] Benchmark"
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --manifest-path zkcrypto/Cargo.toml

      - name: "[zkcrypto] Benchmark (parallel)"
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --manifest-path zkcrypto/Cargo.toml --features parallel
