name: zkcrypto tests

on: [push, pull_request, workflow_dispatch]

env:
  C_KZG_4844_GIT_HASH: '624aa60d01da524827123506975431aa5454c80d'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py_ecc
          pip install PyYAML

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: "[zkcrypto] Tests"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path zkcrypto/Cargo.toml --no-fail-fast

      - name: "[zkcrypto] Tests (parallel)"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path zkcrypto/Cargo.toml --no-fail-fast --features parallel

      - name: "[zkcrypto] Tests (c-kzg-4844)"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd zkcrypto && bash run-c-kzg-4844-tests.sh

      - name: "[zkcrypto] Tests (c-kzg-4844 parallel)"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd zkcrypto && bash run-c-kzg-4844-tests.sh --parallel

      - name: "[zkcrypto] Clippy"
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path zkcrypto/Cargo.toml --all-targets --all-features -- -D warnings

      - name: "[zkcrypto] Formatting"
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path zkcrypto/Cargo.toml -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path kzg-bench/Cargo.toml -- --check
