[package]
name = "kzg-bench"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kzg = { path = '../kzg' }
#blst = { 'git' = 'https://github.com/supranational/blst.git' }
rand = "0.8.4"
criterion = "0.3.5"